### PR TITLE
Fix/475 delete profile

### LINKED ISSUE #475: Implement group deletion when owner deletes profile

### PR DESCRIPTION
**Pull request by claumnl**
# Description

This PR introduces a dedicated user account deletion use case that safely removes a user and all associated data (groups, events, focus sessions, todos, profile metadata) while respecting repository boundaries and Firestore consistency constraints.
It closes #475.

## Changes

- Introduced a DeleteUserAccountUseCase to orchestrate full account deletion across repositories.

- Refactored ProfileRepository.deleteProfile to focus on profile-owned data only (profile document, username, profile picture).

- Ensured deleted users are removed from groups they are members of.

- Ensured groups where deleted user is the owner are deleted.

- Ensured deleted users are removed from events participant lists.

#### Added

- DeleteUserAccountUseCase.kt
- DeleteUserAccountUseCaseTest.kt

#### Modified

- ProfileRepositoryFirestore.kt
- ProfileLocalRepository.kt
- ProfileRepository.kt
- ProfileRepositoryFirestoreTest.kt
- FriendsViewModel.kt (it was overriding a profile local repo)

## Testing

Line coverage: 92.9%

### CODE REVIEW

File: app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt [hunk 1]
```diff
@@ -0,0 +1,197 @@
...
+            profileRepository = profileRepo,
+            groupsRepository = groupsRepo,
+            eventsRepository = eventsRepo,
+            focusSessionsRepository = focusRepo,
+            todosRepository = todosRepo)
+  }
+
+  @Test
+  fun deleteUserAccount_deletesOwnedGroups() = runTest {
+    val group =
```
Comment (AACioffi) [inline app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt]: Suggestion: I see you create several groups with different characteristics in the tests. I believe using the Kotlin Object approach described above would make the code more readable: just move the currently defined group objects into the Kotlin Object.

File: app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt [hunk 2]
```diff
@@ -0,0 +1,197 @@
...
+        DeleteUserAccountUseCase(
+            profileRepository = profileRepo,
+            groupsRepository = groupsRepo,
+            eventsRepository = eventsRepo,
+            focusSessionsRepository = focusRepo,
+            todosRepository = todosRepo)
+  }
+
+  @Test
+  fun deleteUserAccount_deletesOwnedGroups() = runTest {
```
[the remark this answers is not in the document]
Comment (claumnl) [reply app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt]: Thank you for your comment I refactored it!

File: app/src/main/java/com/android/gatherly/utils/DeleteUserAccountUseCase.kt [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+   * - Groups owned by the user are deleted.
+   * - The user is removed from groups they are a member of.
+   * - Events created by the user are deleted.
+   * - User is removed from participant lists of events he participated in.
+   * - Focus sessions created by the user are deleted.
+   * - Todos owned by the user are deleted.
+   * - The user profile is deleted last.
+   *
+   * @param userId The UID of the user whose account should be deleted.
+   * @throws Exception if any deletion step fails. Partial deletion may have occurred.
```
[the remark this answers is not in the document]
Comment (AACioffi) [reply app/src/main/java/com/android/gatherly/utils/DeleteUserAccountUseCase.kt]: Fair enough.

**Review by AACioffi — COMMENTED** [review]
Much better this way.

File: app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt
Comment (AACioffi) [inline app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt]: I don't know if GitHub is messing with me, but the web UI is still showing the presence of userId and otherUserId. Are they actually still there? If so, wouldn't it be better to extract these and place them inside the TestData Object as well?

Comment (claumnl) [reply app/src/test/java/com/android/gatherly/utilstest/DeleteUserAccountUseCaseTest.kt]: You're right I just forgot to take them out, they were unused. It is done now.

**Review by AACioffi — APPROVED** [review]
LGTM
