### PR TITLE
Feat/136 Implement events and fix todos in map

### LINKED ISSUE #136: Map Events UI
Edit MapScreen to implement events and change prior code to clean the ui.

### PR DESCRIPTION
**Pull request by coco-jrdn**
# Description
This PR implements events in the map and fixes prior todos in map.
 It closes #136 

## Changes

Todos shown are from the firebase repository and the camera centers on the first todo/event found or on EPFL.
Events are now shown on map and can be expanded like todos.
A toggle button switch between filtering todos or events.

#### Modified
- MapScreen
- MapViewModel
## Testing
- MapScreenTest

Added tests to check if button and map is displayed and if icons elements are well displayed too

#### SonarCloud Line Coverage
The code achieved > 80% line coverage on the map UI tests.

Screenshot 2025-11-06 at 23 30 42

## Screenshots (if applicable)
Todo Marker
image image

Event Marker
imageimage

### CODE REVIEW

File: app/src/main/java/com/android/gatherly/ui/map/MapScreen.kt [hunk 1]
```diff
@@ -83,49 +92,83 @@ fun MapScreen(
...
+                          true
+                        })
+                  }
+                  is Event -> {
+                    val loc = item.location ?: return@forEach
+                    val isExpanded = uiState.expandedItemId == item.id
+
+                    val formattedDate =
+                        remember(item.date) {
+                          val sdf = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault())
```
Comment (gkerjan) [inline app/src/main/java/com/android/gatherly/ui/map/MapScreen.kt]: Optional : This SimpleDateFormat is declared in 2 different places I think it would be possible to declare it higher one, and use it in both places

File: app/src/main/java/com/android/gatherly/ui/map/MapViewModel.kt [hunk 2]
```diff
@@ -132,6 +140,22 @@ class MapViewModel(
     }
   }
 
+  fun refreshUIState() {
```
Comment (gkerjan) [inline app/src/main/java/com/android/gatherly/ui/map/MapViewModel.kt]: There is a lot of repitition of code here, instead of repeating the same code in init and refreshUIState, just cal refreshUIState in init

File: app/src/main/java/com/android/gatherly/ui/map/MapScreen.kt [hunk 3]
```diff
@@ -83,178 +123,269 @@ fun MapScreen(
...
+      floatingActionButton = {
+        val isEvents = uiState.displayEventsPage
+        ExtendedFloatingActionButton(
+            onClick = { viewModel.changeView() },
+            text = {
+              Text(
+                  if (uiState.displayEventsPage) stringResource(R.string.show_todos_button_title)
+                  else stringResource(R.string.show_events_button_title))
+            },
+            icon = {},
```
[the remark this answers is not in the document]
Comment (coco-jrdn) [reply app/src/main/java/com/android/gatherly/ui/map/MapScreen.kt]: Yes it is. We didn't want to put an icon in this FloatingActionButton for now.
It is necessary to still fill the icon parameter for the Button to exist.
