### PR TITLE
Fix/184 deterministic tests

### LINKED ISSUE #118: Refactor test directories

### LINKED ISSUE #184: Review all tests and check that they are deterministic

### PR DESCRIPTION
**Pull request by gkerjan**
# Description
The PR fixes the determinism of tests present on the main branch. It was needed because the CI needs to be launched multiple times for all tests to pass, and this fixes that.

## Changes
This issue was created due to problems on the main branch of tests that are not deterministic because of Firestore or because the default time limit for a test (10 seconds) is not enough for some tests to run on the CI. After some research, I came to the conclusion that only Firestore repository tests should make calls to Firebase emulators, and UI and VM tests should use already defined local repositories for time deterministic and efficient tests. The second issue was created due to inconsistencies in where test files are created in the project. It closes #184 and closes #118 

## Files 

- All or most test files. (Some were removed their dependency on Firestore, some were refactored to use already existing local repositories instead of test ones)
- ToDosLocalRepository.kt (previously ToDosRepositoryLocalMapTest.kt, was modified to be a true local repository, not just hardcoded for map testing)
- Some viewModels (were modified to include a currentUser that defaults to the Firebase auth current user, but can be set to another value for testing)
- SettingsScreen.kt (was changed so that the dealing with the currentUser is left to the viewModel rather than the UI)
- app/build.gradle.kts (was modified to increase the timeout value to 30 seconds instead of 10 on tests)
- Some files were deleted, either because git considers I deleted them even though I just moved them, because there were still files left from the sample app, or some files are now obsolete test local repositories that were replaced with the ones we already have in the projet.

## Testing

Line coverage is at 88.9%.

## Things to note

There are a lot of lines of code to review in this PR, because sometimes git considers that I created new files when I just moved them and changed a few lines, or that I wrote some lines of code that I didn't simply because they were moved two spaces to the left. The tests in themselves are usually either not changed, or a variable or function that they use had to be changed because the structure of the class changed. The things to pay particular attention to are usually the setUp and tearDown functions in the test suites.

### CODE REVIEW

File: app/src/androidTest/java/com/android/gatherly/utils/FirestoreFocusSessionsGatherlyTest.kt [hunk 1]
```diff
@@ -29,15 +29,12 @@ open class FirestoreFocusSessionsGatherlyTest {
   // Create fake tokens for different users
   protected val user1Token = FakeJwtGenerator.createFakeGoogleIdToken("User1", "user1@test.com")
   protected val user2Token = FakeJwtGenerator.createFakeGoogleIdToken("User2", "user2@test.com")
-  protected val user3Token = FakeJwtGenerator.createFakeGoogleIdToken("User3", "user3@test.com")
```
Comment (claumnl) [inline app/src/androidTest/java/com/android/gatherly/utils/FirestoreFocusSessionsGatherlyTest.kt]: Question: Here what made you delete user3Token ?

File: app/src/test/java/com/android/gatherly/viewmodel/event/AddEventsViewModelTest.kt [hunk 2]
```diff
@@ -36,36 +33,28 @@ class AddEventsViewModelTest {
...
   fun setUp() {
     // so that tests can wait on coroutines
     Dispatchers.setMain(testDispatcher)
-
-    if (!FirebaseEmulator.isRunning) {
-      error("Firebase emulator must be running! Use: firebase emulators:start")
-    }
-    runTest {
-      FirebaseEmulator.auth.signInAnonymously().await()
-      ownerProfile = ownerProfile.copy(uid = Firebase.auth.currentUser?.uid!!)
```
Comment (claumnl) [inline app/src/test/java/com/android/gatherly/viewmodel/event/AddEventsViewModelTest.kt]: Question: Here, you took out ownerProfile, where do we take care of the user signing in now?

File: app/src/test/java/com/android/gatherly/viewmodel/event/AddEventsViewModelTest.kt [hunk 3]
```diff
@@ -36,36 +33,28 @@ class AddEventsViewModelTest {
   private lateinit var profileRepository: ProfileRepository
 
   // initialize this so that tests control all coroutines and can wait on them
-  private val testDispatcher = UnconfinedTestDispatcher()
+  private val testDispatcher = StandardTestDispatcher()
```
Comment (claumnl) [inline app/src/test/java/com/android/gatherly/viewmodel/event/AddEventsViewModelTest.kt]: Question: From now on should this be standard practice for our test files?

File: app/src/test/java/com/android/gatherly/viewmodel/friends/FriendsViewModelTest.kt [hunk 4]
```diff
@@ -83,14 +96,7 @@ class FriendsViewModelTest {
   fun testFollowFriendCFromProfileA() = runTest {
     viewModel.followFriend("C", "A")
 
-    // Wait until the friends list is updated
-    withContext(Dispatchers.Default.limitedParallelism(1)) {
```
Comment (claumnl) [inline app/src/test/java/com/android/gatherly/viewmodel/friends/FriendsViewModelTest.kt]: Question: From now on, in view model tests, should we always use advanceUntilIdle() instead of withTimeout?

File: app/src/test/java/com/android/gatherly/viewmodel/homepage/HomePageViewModelTest.kt [hunk 5]
```diff
@@ -301,35 +288,24 @@ class HomePageViewModelTest {
       profileRepository.addProfile(friend4Profile)
       eventsRepository.addEvent(event1)
       eventsRepository.addEvent(event2)
-      toDosRepository.deleteTodo("1")
-      toDosRepository.deleteTodo("2")
```
Comment (claumnl) [inline app/src/test/java/com/android/gatherly/viewmodel/homepage/HomePageViewModelTest.kt]: Question: If we don't delete the todos here, where do we do it ?

**Review by claumnl — COMMENTED** [review]
Thank you for this pr! Refactoring the tests is really going to improve the chances to pass the ci! I wrote down mostly questions as it concerns a lot of different code including some I am not familiar with. As soon as you go through my questions, I will approve this pr. Again, really nice refacoring!

File: app/src/androidTest/java/com/android/gatherly/ui/events/AddEventsViewModelTest.kt [hunk 6]
```diff
@@ -36,36 +33,28 @@ class AddEventsViewModelTest {
...
   fun setUp() {
     // so that tests can wait on coroutines
     Dispatchers.setMain(testDispatcher)
-
-    if (!FirebaseEmulator.isRunning) {
-      error("Firebase emulator must be running! Use: firebase emulators:start")
-    }
-    runTest {
-      FirebaseEmulator.auth.signInAnonymously().await()
-      ownerProfile = ownerProfile.copy(uid = Firebase.auth.currentUser?.uid!!)
```
Comment (gkerjan) [reply app/src/androidTest/java/com/android/gatherly/ui/events/AddEventsViewModelTest.kt]: The ownerProfile still exists. Now the 'sign in' happens when we set the currentUser value in the viewModel. The currentUser here is set to ownerProfile.uid.

File: app/src/test/java/com/android/gatherly/viewmodel/event/AddEventsViewModelTest.kt (hunk 3 above)
Comment (claumnl) [reply app/src/test/java/com/android/gatherly/viewmodel/event/AddEventsViewModelTest.kt]: So using advanceUntilIdle will not work correctly without this?

**Review by claumnl — APPROVED** [review]
LGTM
