### PR TITLE
Fix/408 Timer Bug Fix

### LINKED ISSUE #408: Fix Timer not validating focus sessions when it expires automatically
Currently, focus sessions are only validated when the user manually presses the Stop button. If the timer runs until the end on its own, the endTimer() function logic is not correctly triggered so the focus session is not marked as completed.

### PR DESCRIPTION
**Pull request by coco-jrdn**
# Description
This PR fixes the timer when a focus session ends naturally. 
This PR also fixes focus points not being shown on the user profile.
It closes #408

## What was wrong

Previously, focus sessions were only finalized when the user manually pressed Stop.
When the countdown reached zero, the endTimer() logic was not executed properly so the session was not marked as completed and related updates were missing (focus points and badges).

## What’s fixed

Fixed the timer naturally finishing by correcting startTicking() logic that bypassed endTimer() when Duration arrived to ZERO
Focus sessions are now finalized whether the user stops manually or the timer runs out.
Updated the elapsedTime logic that caused FocusPoints UI to always show 0 minutes.
Focus points are correctly updated and displayed on the profile.

#### Modified
- ProfileViewModel
- TimerViewModel

## Testing 
image

## Screenshots
image 
image

### CODE REVIEW

File: app/src/main/java/com/android/gatherly/ui/focusTimer/TimerViewModel.kt [hunk 1]
```diff
@@ -365,15 +377,16 @@ class TimerViewModel(
...
           }
 
-          _uiState.value = state.copy(remainingTime = remaining)
+          _uiState.value = state.copy(remainingTime = remaining, elapsedTime = elapsed)
           updateClock(remaining)
 
           if (remaining <= Duration.ZERO) {
-            elapsedTime = state.plannedDuration
-            _uiState.value = _uiState.value.copy(isStarted = false, isPaused = false)
-            updateClock(Duration.ZERO)
```
Comment (gkerjan) [inline app/src/main/java/com/android/gatherly/ui/focusTimer/TimerViewModel.kt]: Question: since `isStarted` and `isPaused`, and tu clock are not updated here, are they updated elsewhere (like in endTimer?) or are they never updated and if so, why?

File: app/src/main/java/com/android/gatherly/ui/focusTimer/TimerViewModel.kt [hunk 2]
```diff
@@ -415,7 +425,7 @@ class TimerViewModel(
   }
 
   /**
-   * Sets an error message in the UI state.
+   * Sets an er338ror message in the UI state.
```
Comment (gkerjan) [inline app/src/main/java/com/android/gatherly/ui/focusTimer/TimerViewModel.kt]: You should fix this :)

Comment (coco-jrdn) [reply app/src/main/java/com/android/gatherly/ui/focusTimer/TimerViewModel.kt]: I've fixed that now :)

**Review by gkerjan — APPROVED** [review]
Looks good to me!
