### PR TITLE
Fix/246-factory-vm

### LINKED ISSUE #246: Create and use ViewModel factory function
Correction as coach feedback suggestions : Instead of declaring the ViewModel factory directly in the Composable, it would be cleaner to define a static provideFactory function inside the corresponding ViewModel. This keeps UI code focused on presentation and encapsulates ViewModel creation logic within the ViewModel itself.

### PR DESCRIPTION
**Pull request by clairechaffard**
# Description
This PR introduces the function `provideFactory` for the 3 events VM and called it in their ui.  It was a correction suggested in one of the feedback. 
Closes #246 

#### Modified
- `AddEventScreen.kt`: Modified how the ViewModel is created with calling the new function for his factory 
- `AddEventViewModel.kt`:  Created the function `provideFactory` with specific dependencies with profile repository 
- `EditEventScreen.kt`: Modified how the ViewModel is created with calling the new function for his factory 
- `EditEventViewModel.kt`:  Created the function `provideFactory` with specific dependencies with profile repository 
- `EventsScreen.kt`: Modified how the ViewModel is created with calling the new function for his factory
- `EventsViewModel.kt`: Created the function `provideFactory`

## Testing: No testing since this is only a modification in already tested files

### CODE REVIEW

File: app/src/main/java/com/android/gatherly/ui/events/EventsScreen.kt [hunk 1]
```diff
@@ -118,7 +113,8 @@ object EventsScreenTestTags {
  * @param navigateToEditEvent Callback to navigate to the event editing screen with the selected
  *   event
  * @param navigationActions Handles navigation between different tabs/screens.
- * @param eventsViewModel The ViewModel managing the state and logic for the Events screen.
+ * @param eventsViewModel The ViewModel managing the state and logic for the Events screen, calling
```
[the remark this answers is not in the document]
Comment (clairechaffard) [reply app/src/main/java/com/android/gatherly/ui/events/EventsScreen.kt]: Thanks you for noticing this. I modified this.

File: app/src/main/java/com/android/gatherly/ui/events/AddEventScreen.kt [hunk 2]
```diff
@@ -70,8 +70,8 @@ object AddEventScreenTestTags {
 /**
  * Screen for adding an existing Event.
  *
- * @param addEventViewModel calling with the ViewModel declaration factory which is within a
- *   Composable function
+ * @param addEventViewModel The ViewModel managing the state and logic for the Edit Event screen,
```
Comment (AACioffi) [inline app/src/main/java/com/android/gatherly/ui/events/AddEventScreen.kt]: Nitpick: Should be "Add Event screen" instead of "Edit Event screen".

Comment (clairechaffard) [reply app/src/main/java/com/android/gatherly/ui/events/AddEventScreen.kt]: Thanks you for noticing this, sorry, I went too fast.
